name: Selenium IDE Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install NuGet packages
      run: dotnet restore

    - name: Build the test project
      run: dotnet build --no-restore

    - name: Install Edge and EdgeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-stable
        sudo apt-get install -y microsoft-edge-webdriver


    - name: Run tests
      run: dotnet test --logger trx --results-directory TestResults
